In [1]:
import pandas as pd

In [2]:
# =====================================================
# Load Dataset & Basic Preprocessing
# =====================================================

df = pd.read_csv('../Data/uber_taxi_demand_5years.csv')
df['datetime'] = pd.to_datetime(df['datetime'])
df.head(10)

,datetime,zone,pickup_count,temperature,precipitation,is_holiday,is_raining
0,2021-01-01 00:00:00,Airport,42,1.7,0.0,1,0
1,2021-01-01 00:00:00,Downtown,77,1.7,0.0,1,0
2,2021-01-01 00:00:00,Midtown,16,1.7,0.0,1,0
3,2021-01-01 00:00:00,Suburb,3,1.7,0.0,1,0
4,2021-01-01 00:00:00,Uptown,12,1.7,0.0,1,0
5,2021-01-01 01:00:00,Airport,52,-3.1,0.0,1,0
6,2021-01-01 01:00:00,Downtown,81,-3.1,0.0,1,0
7,2021-01-01 01:00:00,Midtown,19,-3.1,0.0,1,0
8,2021-01-01 01:00:00,Suburb,3,-3.1,0.0,1,0
9,2021-01-01 01:00:00,Uptown,10,-3.1,0.0,1,0

In [3]:
print("Total Rows In The Dataset:",df.shape[0])
print("Total Columns In The Dataset:",df.shape[1],"\n")

print("Columns Names: ",df.columns,"\n")

print(f"Date Range: {df['datetime'].min()} to {df['datetime'].max()}")

total_days = (df['datetime'].max() - df['datetime'].min()).days
total_years = total_days / 365.25
print(f"Total Year: {total_years:.1f} Years (approx {total_days} days)")

Total Rows In The Dataset: 219120
Total Columns In The Dataset: 7

Columns Names:  Index(['datetime', 'zone', 'pickup_count', 'temperature', 'precipitation',
       'is_holiday', 'is_raining'],
      dtype='object')

Date Range: 2021-01-01 00:00:00 to 2025-12-31 23:00:00
Total Year: 5.0 Years (approx 1825 days)

In [4]:
print("Missing Values In The Dataset:")
print(df.isnull().sum())

Missing Values In The Dataset:
datetime         0
zone             0
pickup_count     0
temperature      0
precipitation    0
is_holiday       0
is_raining       0
dtype: int64

In [5]:
print("Data Info:")
print(df.info())

Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219120 entries, 0 to 219119
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   datetime       219120 non-null  datetime64[ns]
 1   zone           219120 non-null  object
 2   pickup_count   219120 non-null  int64
 3   temperature    219120 non-null  float64
 4   precipitation  219120 non-null  float64
 5   is_holiday     219120 non-null  int64
 6   is_raining     219120 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(3), object(1)
memory usage: 11.7+ MB
None

In [6]:
df.describe()

,datetime,pickup_count,temperature,precipitation,is_holiday,is_raining
count,219120,219120.000000,219120.000000,219120.000000,219120.000000,219120.000000
mean,2023-07-02 23:29:59.999999744,39.387532,13.996650,0.545411,0.013691,0.160300
min,2021-01-01 00:00:00,0.000000,-9.200000,0.000000,0.000000,0.000000
25%,2022-04-02 11:45:00,11.000000,4.600000,0.000000,0.000000,0.000000
50%,2023-07-02 23:30:00,29.000000,14.000000,0.000000,0.000000,0.000000
75%,2024-10-01 11:15:00,58.000000,23.400000,0.000000,0.000000,0.000000
max,2025-12-31 23:00:00,571.000000,36.400000,23.900000,1.000000,1.000000
std,NaN,36.268009,10.313007,1.603143,0.116206,0.366885

In [7]:
print("Total Unique Values In All Columns:")
print(df.nunique().sort_values())

Total Unique Values In All Columns:
is_raining           2
is_holiday           2
zone                 5
precipitation      152
pickup_count       298
temperature        440
datetime         43824
dtype: int64

In [8]:
print("Zone Distribution:")
print(df['zone'].value_counts().sort_values())

Zone Distribution:
zone
Airport     43824
Downtown    43824
Midtown     43824
Suburb      43824
Uptown      43824
Name: count, dtype: int64

In [9]:
print("Holiday Distribution:")
print(df['is_holiday'].value_counts().sort_values())

Holiday Distribution:
is_holiday
1      3000
0    216120
Name: count, dtype: int64

In [10]:
print("Raining Distribution:")
print(df['is_raining'].value_counts().sort_values())

Raining Distribution:
is_raining
1     35125
0    183995
Name: count, dtype: int64

In [11]:
print(f"Memory Usage: {df.memory_usage(deep=True).sum()/1024**2:.2f} MB")
print(df.dtypes)

Memory Usage: 23.36 MB
datetime         datetime64[ns]
zone                     object
pickup_count              int64
temperature             float64
precipitation           float64
is_holiday                int64
is_raining                int64
dtype: object