In [1]:
import pandas as pd

In [2]:
# =====================================================
# Load Dataset & Basic Preprocessing
# =====================================================

df = pd.read_csv('../Data/data.csv')
df.head(5)

D:\Temp\ipykernel_7988\900381609.py:5: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../Data/data.csv')

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,3,2014-12-31,2605,327,1,0,0,1
1,2,3,2014-12-31,2269,252,1,0,0,1
2,3,3,2014-12-31,3804,408,1,0,0,1
3,4,3,2014-12-31,10152,1311,1,0,0,1
4,5,3,2014-12-31,1830,217,1,0,0,1

In [3]:
print("Total Rows In The Dataset:",df.shape[0])
print("Total Columns In The Dataset:",df.shape[1],"\n")

print("Columns Names: ",df.columns,"\n")

print(f"Date Range: {df['Date'].min()} to {df['Date'].max()}")

Total Rows In The Dataset: 780829
Total Columns In The Dataset: 9

Columns Names:  Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday'],
      dtype='object')

Date Range: 2013-01-01 to 2014-12-31

In [4]:
print("Missing Values In The Dataset:")
print(df.isnull().sum())

Missing Values In The Dataset:
Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [5]:
df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)   

df['StateHoliday'] = df['StateHoliday'].astype(str)
df.drop("DayOfWeek", axis=1, inplace=True)

In [6]:
print("Data Info:")
print(df.info())

Data Info:
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 780829 entries, 2014-12-31 to 2013-01-01
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Store          780829 non-null  int64
 1   Sales          780829 non-null  int64
 2   Customers      780829 non-null  int64
 3   Open           780829 non-null  int64
 4   Promo          780829 non-null  int64
 5   StateHoliday   780829 non-null  object
 6   SchoolHoliday  780829 non-null  int64
dtypes: int64(6), object(1)
memory usage: 47.7+ MB
None

In [7]:
df.describe()

,Store,Sales,Customers,Open,Promo,SchoolHoliday
count,780829.000000,780829.000000,780829.000000,780829.000000,780829.000000,780829.000000
mean,558.559818,5742.206014,635.854196,0.830348,0.375633,0.187542
std,321.919437,3852.310932,467.815283,0.375327,0.484286,0.390346
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,281.000000,3683.000000,403.000000,1.000000,0.000000,0.000000
50%,558.000000,5691.000000,611.000000,1.000000,0.000000,0.000000
75%,838.000000,7811.000000,841.000000,1.000000,1.000000,0.000000
max,1115.000000,38037.000000,7388.000000,1.000000,1.000000,1.000000

In [8]:
print("Total Unique Values In All Columns:")
print(df.nunique().sort_values())

Total Unique Values In All Columns:
Open                 2
Promo                2
SchoolHoliday        2
StateHoliday         4
Store             1115
Customers         4000
Sales            20937
dtype: int64

In [9]:
print("Promo Distribution:")
print(df['Promo'].value_counts().sort_values())

Promo Distribution:
Promo
1    293305
0    487524
Name: count, dtype: int64

In [10]:
print("SchoolHoliday Distribution:")
print(df['SchoolHoliday'].value_counts().sort_values())

SchoolHoliday Distribution:
SchoolHoliday
1    146438
0    634391
Name: count, dtype: int64

In [11]:
print("StateHoliday Distribution:")
print(df['StateHoliday'].value_counts().sort_values())

StateHoliday Distribution:
StateHoliday
c      4100
b      4460
a     14761
0    757508
Name: count, dtype: int64

In [12]:
print("Open Distribution:")
print(df['Open'].value_counts().sort_values())

Open Distribution:
Open
0    132469
1    648360
Name: count, dtype: int64

In [13]:
print(f"Memory Usage: {df.memory_usage(deep=True).sum()/1024**2:.2f} MB")
print(df.dtypes)

Memory Usage: 84.89 MB
Store             int64
Sales             int64
Customers         int64
Open              int64
Promo             int64
StateHoliday     object
SchoolHoliday     int64
dtype: object