In [22]:
import pandas as pd

In [23]:
# =====================================================
# Load Dataset & Basic Preprocessing
# =====================================================

df = pd.read_csv('../Data/TCS_stock_data.csv')
df['Date'] = pd.to_datetime(df['Date'])
df.head(5)

        Date    Open    High     Low   Close    Volume
0 2010-01-01  421.25  421.25  418.03  420.00   4608027
1 2010-01-04  418.24  434.01  418.24  430.67  16619599
2 2010-01-05  430.84  442.45  430.84  438.77   9933699
3 2010-01-06  437.92  438.20  437.24  437.73   2560889
4 2010-01-07  438.48  441.55  430.75  436.70   2281757

In [24]:
print("Total Rows In The Dataset:",df.shape[0])
print("Total Columns In The Dataset:",df.shape[1],"\n")

print("Columns Names: ",df.columns,"\n")

print(f"Date Range: {df['Date'].min()} to {df['Date'].max()}\n")

total_days = (df['Date'].max() - df['Date'].min()).days
total_years = total_days / 365.25
print(f"Total Year: {total_years:.1f} Years (approx {total_days} days)")

Total Rows In The Dataset: 3850
Total Columns In The Dataset: 6

Columns Names:  Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

Date Range: 2010-01-01 00:00:00 to 2024-12-31 00:00:00

Total Year: 15.0 Years (approx 5478 days)

In [25]:
print("Missing Values In The Dataset:")
print(df.isnull().sum())

Missing Values In The Dataset:
Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [26]:
print("Data Info:")
print(df.info())

Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3850 entries, 0 to 3849
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3850 non-null   datetime64[ns]
 1   Open    3850 non-null   float64
 2   High    3850 non-null   float64
 3   Low     3850 non-null   float64
 4   Close   3850 non-null   float64
 5   Volume  3850 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 180.6 KB
None

In [27]:
df.describe()

,Date,Open,High,Low,Close,Volume
count,3850,3850.000000,3850.000000,3850.000000,3850.000000,3.850000e+03
mean,2017-06-30 17:29:08.571428608,3846.668039,3887.919010,3801.800657,3844.015564,4.321025e+06
min,2010-01-01 00:00:00,375.080000,379.510000,371.990000,375.600000,1.805769e+06
25%,2013-09-26 06:00:00,1216.932500,1241.847500,1212.435000,1226.927500,3.014617e+06
50%,2017-07-01 12:00:00,3459.640000,3507.565000,3427.935000,3461.280000,4.032496e+06
75%,2021-04-01 18:00:00,6420.777500,6484.822500,6337.525000,6417.362500,5.084359e+06
max,2024-12-31 00:00:00,10323.560000,10388.450000,10243.990000,10312.710000,1.945866e+07
std,NaN,2818.633303,2847.106211,2785.133827,2814.895646,2.093890e+06

In [28]:
print(f"Memory Usage: {df.memory_usage(deep=True).sum()/1024**2:.2f} MB")
print(df.dtypes)

Memory Usage: 0.18 MB
Date      datetime64[ns]
Open             float64
High             float64
Low              float64
Close            float64
Volume             int64
dtype: object